name: CI Pipeline
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache: true
      - name: Run tests
        run: |
          go test -v -race ./test/...
          go test -v -race ./myipld/
          go test -v -race ./bench/
      - name: Run benchmarks
        run: |
          go test -bench=. -benchmem ./test/ > benchmark_results.txt
          cat benchmark_results.txt